package com.jpassbolt.api.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTOs for the CE password-policies settings API
 * ({@code GET /password-policies/settings.json}), porting the PHP
 * {@code Passbolt\PasswordPolicies\Model\Dto\PasswordPoliciesSettingsDto} and its
 * two nested generator-settings DTOs.
 *
 * <p>
 * In CE these settings are ALWAYS the built-in defaults with
 * {@code source = "default"} — the database write path is EE-only — so this is a
 * pure defaults projection: no storage, no admin gate, just an authenticated
 * read. The defaults live in {@code PasswordPoliciesService.getSettings()}, not
 * here (iron law 3: DTOs carry no business logic, only transport + snake_case
 * mapping).
 * </p>
 *
 * <p>
 * The CE response only ever emits the five {@code source = "default"} fields
 * ({@code default_generator}, {@code password_generator_settings},
 * {@code passphrase_generator_settings}, {@code source},
 * {@code external_dictionary_check}); the EE-only DB columns
 * ({@code id}/{@code created}/{@code created_by}/{@code modified}/
 * {@code modified_by}) are omitted, mirroring PHP {@code toArray()} which only
 * adds them when {@code source === 'db'}.
 * </p>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PasswordPoliciesSettingsDto {

    @JsonProperty("default_generator")
    private String defaultGenerator;

    @JsonProperty("external_dictionary_check")
    private Boolean externalDictionaryCheck;

    @JsonProperty("password_generator_settings")
    private PasswordGeneratorSettings passwordGeneratorSettings;

    @JsonProperty("passphrase_generator_settings")
    private PassphraseGeneratorSettings passphraseGeneratorSettings;

    @JsonProperty("source")
    private String source;

    /**
     * Settings used when a password is generated by the password generator
     * (PHP {@code PasswordGeneratorSettingsDto}).
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class PasswordGeneratorSettings {

        @JsonProperty("length")
        private Integer length;

        @JsonProperty("mask_upper")
        private Boolean maskUpper;

        @JsonProperty("mask_lower")
        private Boolean maskLower;

        @JsonProperty("mask_digit")
        private Boolean maskDigit;

        @JsonProperty("mask_parenthesis")
        private Boolean maskParenthesis;

        @JsonProperty("mask_emoji")
        private Boolean maskEmoji;

        @JsonProperty("mask_char1")
        private Boolean maskChar1;

        @JsonProperty("mask_char2")
        private Boolean maskChar2;

        @JsonProperty("mask_char3")
        private Boolean maskChar3;

        @JsonProperty("mask_char4")
        private Boolean maskChar4;

        @JsonProperty("mask_char5")
        private Boolean maskChar5;

        @JsonProperty("exclude_look_alike_chars")
        private Boolean excludeLookAlikeChars;
    }

    /**
     * Settings used when a passphrase is generated by the password generator
     * (PHP {@code PassphraseGeneratorSettingsDto}).
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class PassphraseGeneratorSettings {

        @JsonProperty("words")
        private Integer words;

        @JsonProperty("word_separator")
        private String wordSeparator;

        @JsonProperty("word_case")
        private String wordCase;
    }
}
